export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGOUT='LOGOUT'
export const LOGIN_USER='LOGIN_USER'
export const ON_LOADING='ON_LOADING'
export const ON_ERROR='ON_ERROR'
export const SET_USER='SET_USER'